spring:
  jpa:
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  datasource:
    public-ip:
      url: jdbc:postgresql:///
      database: my-database1
      cloudSqlInstance: <MY_PROJECT_ID>:us-central1:main-instance
      username: henry
      password: mypassword
      ipTypes: PUBLIC
      socketFactory: com.google.cloud.sql.postgres.SocketFactory
      driverClassName: org.postgresql.Driver
    private-ip:
      url: jdbc:postgresql:///
      database: my-database2
      cloudSqlInstance: <MY_PROJECT_ID>:us-central1:private-instance
      username: henry
      password: mypassword
      ipTypes: PRIVATE
      socketFactory: com.google.cloud.sql.postgres.SocketFactory
      driverClassName: org.postgresql.Driver
